### ISSUE TITLE
Add mechanism for users to add release labels if one isn't present

### ISSUE THREAD

**Issue by just-be-dev** [zephraph/autobot#14]
This feature will append a label list to a PR that guides/enables the creator of the PR to add the appropriate labels. An example of the flow below.

---

<img align="left" width="60" src="https://autobot.auto-it.now.sh/public/logo.png"/>

### Choose a release label

This repository uses [auto](https://github.com/intuit/auto) to generate releases. In order to do that, it needs an appropriate label assigned to each PR. Choose a label below that you feel best suites your changes. 

##

<sub>**Semver Labels** _(choose at most one)_</sub> <img title="Determines the version to be released. If none are selected a patch version will be released unless a skip label is selected." align="center" src="https://autobot.auto-it.now.sh/l/octicon/info"/>

- [x] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=FA6900&text=Version: Major"/> &nbsp;&nbsp;<sub><b>Use for breaking changes</b></sub>  	
- [x] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=e0e4cc&text=Version: Minor"/> &nbsp;&nbsp;<sub><b>Use for new features</b></sub>
- [ ] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=e0e4cc&text=Version: Patch"/> &nbsp;&nbsp;<sub><b>Use for bug fixes</b></sub>

<sub>**_⚠️ Only one semver label can be selected_**</sub>

##

<sub>**Skip Release Labels**</sub>

- [ ] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=a7dbd8&text=Version: Trivial"/> &nbsp;&nbsp;<sub><b>Use for non-code related changes</b></sub>
- [ ] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=f7da74&text=Skip Release"/> &nbsp;&nbsp;<sub><b>Use to skip this release</b></sub>

##

<sub>_Generated by [auto-it](https://github.com/apps/auto-it)_</sub>

---

<details>
<summary><b>Choose a release label</b></summary>

&nbsp;
<img align="left" width="60" src="https://autobot.auto-it.now.sh/public/logo.png"/> This repository uses [auto](https://github.com/intuit/auto) to generate releases. In order to do that, it needs an appropriate label assigned to each PR. Choose a label below that you feel best suites your changes. 

##

<sub>**Semver Labels** _(choose at most one)_</sub> <img title="Determines the version to be released. If none are selected a patch version will be released unless a skip label is selected." align="center" src="https://autobot.auto-it.now.sh/l/octicon/info"/>

- [x] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=FA6900&text=Version: Major"/> &nbsp;&nbsp;<sub><b>Use for breaking changes</b></sub>  	
- [x] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=e0e4cc&text=Version: Minor"/> &nbsp;&nbsp;<sub><b>Use for new features</b></sub>
- [ ] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=e0e4cc&text=Version: Patch"/> &nbsp;&nbsp;<sub><b>Use for bug fixes</b></sub>

<sub>**_:warning: Only one semver label can be selected_**</sub>

##

<sub>Skip Release Labels</sub>

- [ ] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=a7dbd8&text=Version: Trivial"/> &nbsp;&nbsp;<sub><b>Use for non-code related changes</b></sub>
- [ ] <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=f7da74&text=Skip Release"/> &nbsp;&nbsp;<sub><b>Use to skip this release</b></sub>

##

</details>

<sub>_Generated by [auto-it](https://github.com/apps/auto-it)_</sub>

**Comment by hipstersmoothie** [comment]
You could maybe have another section called `Contextual Labels`

##

<sub>_**Contextual Labels**_</sub>

- [ ] <img align="center" src="https://autobot.auto-it.now.sh/lambda/label?color=a7dbd8&text=Documentation"/> &nbsp;&nbsp;<sub><b>Changes documentation</b></sub>
- [ ] <img align="center" src="https://autobot.auto-it.now.sh/lambda/label?color=f7da74&text=Blog Post"/> &nbsp;&nbsp;<sub><b>Adds a blog post</b></sub>

<sub>_Generated by [auto-it](https://github.com/apps/auto-it)_</sub>

**Comment by just-be-dev** [comment]
My concern is how we communicate to the user what that label does. It changes which changelog section the PR goes in to. There can only be one changelog label?
